### ISSUE TITLE
Matrix页面刷不出来

### ISSUE THREAD

**Issue by lossatsea** [se-2018/se-2018.github.io#1]

**Comment by LinJinghua** [comment]
请用火狐浏览器。

**Comment by LinJinghua** [comment]
私戳我QQ，或者留下信息，我给你加分，奖励你第一个在github issue上提问。虽然问题描述得不好，较好的例子见[这个](https://github.com/se-2018/se-2018.github.io/issues/2)。

**Comment by wuzht** [comment]
wiki上不了，返回个502
