### ISSUE TITLE
Ant 和 JUnit不能同时使用（学渣可见的问题）

### ISSUE THREAD

**Issue by SongXiaotong** [se-2018/se-2018.github.io#10]
Helloworld.java和HelloworldTest.java放在同一个文件夹的时候，ant找不到jar没办法使用，test移出来就好了
但是这时候junit就不能使用了，，，

**Comment by SongXiaotong** [comment]
用命令行操作要手动include
写编译代码之前要include进junit-4.12.jar
`<fileset dir="${lib.path}">  <include name="**/*.jar" /> </fileset>`
可以定义编译时的classpath，fileset可以查找外部的jar包，查到junit-4.12.jar进行使用

**Comment by SongXiaotong** [comment]
入门级教程https://www.ibm.com/developerworks/cn/java/j-ant/index.html

**Comment by gyakkun** [comment]
建议使用Eclipse Oxygen, 自带ANT导出与JUnit5

下载地址:
https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/oxygen/3a/eclipse-jee-oxygen-3a-linux-gtk-x86_64.tar.gz

![](https://wx1.sinaimg.cn/large/69985a65ly1fqcvqc38x5j20i60h50vh.jpg)

JUnit 用法:

1. 右键需要生成测试文件的类, 选择新建JUnit Test Case
![](https://wx1.sinaimg.cn/large/69985a65ly1fqcvqc2qzrj20i80ecgn6.jpg)

2. 输入测试类名称, 通常在原类名后加Test。Next
![](https://wx4.sinaimg.cn/large/69985a65ly1fqcvqc2mryj20gy0hu3zi.jpg)

3. 勾选需要测试的方法。Finish
![](https://wx4.sinaimg.cn/large/69985a65ly1fqcvqc2owxj20gz0hy3zk.jpg)

4. 生成的测试类中已经根据模板生成了相应测试函数, 自己填入具体测试方法即可
![](https://wx2.sinaimg.cn/large/69985a65ly1fqcvqc3es3j20l80bydhi.jpg)

Ant的用法:
1. 右键需要生成Ant Build.xml的项目, 点击Export(导出)
![](https://wx3.sinaimg.cn/large/69985a65ly1fqcvqc1qorj20ag0awjrq.jpg)

2. 在filter里填ant, 选Ant Buildfiles。 Next
![](https://wx2.sinaimg.cn/large/69985a65ly1fqcvqc1tzoj20gx0f5q39.jpg)

3. 勾选需要导出的项目。注意这里会列出当前打开的所有项目, 根据需要勾选。Finish
![](https://wx2.sinaimg.cn/large/69985a65ly1fqcvqc2kd8j20gx0jaq3q.jpg)

4. 项目根目录下便会自动生成build.xml, 无需手写。
![](https://wx4.sinaimg.cn/large/69985a65ly1fqcw3gyi8tj20k70dcgqb.jpg)

5. 如无意外的话, 在项目目录下运行ant就能编译成功
![](https://wx1.sinaimg.cn/large/69985a65ly1fqcw3gxwufj20ka09gq5h.jpg)
