### ISSUE TITLE
Sonar错误

### ISSUE THREAD

**Issue by Chris-Ju** [se-2018/se-2018.github.io#12]
![](https://github.com/Chris-Ju/Picture/blob/master/JavaModelError.png?raw=true)
sonar-runner时报错，重启后并没有用

**Comment by LinJinghua** [comment]
连接失败，确定开启sonarqube了？

**Comment by gyakkun** [comment]
先配置好环境变量, 见 https://github.com/se-2018/se-2018.github.io/issues/13

**Comment by LinJinghua** [comment]
@Chris-Ju 怎么解决的？分享一下？

**Comment by Chris-Ju** [comment]
1. 配置好好环境变量，楼上链接
2. 配置文件要写好
