### ISSUE TITLE
Ant 运行calculator没界面弹出

### ISSUE THREAD

**Issue by kesongyue** [se-2018/se-2018.github.io#14]
代码没错，用ant测试Helloworld正确，运行calculator没报错但没页面弹出

**Comment by kesongyue** [comment]
在<java>标签里加个fork=“true”就行了

**Comment by LinJinghua** [comment]
相同问题：
[Issue 2](https://github.com/se-2018/se-2018.github.io/issues/7)
[Issue 7](https://github.com/se-2018/se-2018.github.io/issues/7)
