### ISSUE TITLE
BugRunner编译成功但不能运行

### ISSUE THREAD

**Issue by CastleOnTheHill** [se-2018/se-2018.github.io#16]
![_1073114995_img20180415132734_1523770091000_xg_0](https://user-images.githubusercontent.com/31783998/38775284-025019b8-40b1-11e8-9e2c-ceaf437fb86a.jpg)

**Comment by LinJinghua** [comment]
~~编译时加`-d .`试试？~~
哦，他没`package`，你打什么`projects.firstProject.BugRunner`啊。。。
楼下的`java -classpath ./gridworld.jar:projects/firstProjects BugRunner`是正确的，不过多了一个`s`。
可以是`java -cp gridworld.jar:projects\firstProject\ BugRunner`或者`cd projects/firstProject && java -cp .:../../gridworld.jar BugRunner`

此外，问题详情、出错信息应该是复制文字而不只是截图，方便信息检索。

**Comment by dysuby** [comment]
`java -classpath ./gridworld.jar:projects/firstProjects BugRunner`
