### ISSUE TITLE
如何解决Sonar不允许使用ArrayList的问题

### ISSUE THREAD

**Issue by dysuby** [se-2018/se-2018.github.io#17]
> Avoid using implementation types like 'ArrayList'; use the interface instead

major型， 改成List的话会与父类冲突，还有什么办法可以解决吗

**Comment by LinJinghua** [comment]
1.  改源码重新打包jar
2.  禁用规则
3.  排除文件
4.  这个错误不会导致扣分，无视算了

**Comment by cxk1998** [comment]
我感觉第四条是最实用的

**Comment by huangjundashuaige** [comment]
支持改源码
