### ISSUE TITLE
吐槽

### ISSUE THREAD

**Issue by sanfengliao** [se-2018/se-2018.github.io#18]
有些问题根本就没必要贴源码解释，比如说获取location的row，文档都说了getRow是用来获取row的，还要我们贴源码，不是没事找事吗

**Comment by LinJinghua** [comment]
这个可以有。

但是要是加上根据实际情况添加源码，那么评分后肯定有人不满意分数：这题根本不用加，凭什么没分？…………(无异议的标准很重要


要是不在意这点分数的人，可以选择放弃这些问答题的15分啊2333反正也能及格。没有要求所有题目都做啊，觉得恶心就别做了(真的

要是实在不舍得15分，可以选择在其他地方加回来啊。之前在群里有人提议写critter进行决斗，我有回应说，把规则阐述清楚可以考虑作为加分项，但没后文了。你也可以提议一些加分项目来抵消这些问答题的丢分啊。如果真想提议，得尽早，毕竟快结束了。

现在公示的作业，都是几年前的东西了，真诚希望大家提议些新内容。

2018.05.03更新：不再接受加分项目提议。
