### ISSUE TITLE
JAVA-GUI-ANT-运行无程序弹出

### ISSUE THREAD

**Issue by Cai72** [se-2018/se-2018.github.io#2]
问题：执行ant指令后GUI程序没有弹出
猜测原因：需要通过线程防止ant非正常终止GUI程序

**Comment by Cai72** [comment]
解决方案：添加fork属性
i.e *<java classname="" fork="yes"*>

**Comment by LinJinghua** [comment]
相同问题：[ANT  运行程序闪退现象](https://github.com/se-2018/se-2018.github.io/issues/7)
