### ISSUE TITLE
网页上的mazebug包已经给了源码了？

### ISSUE THREAD

**Issue by LovelyBuggies** [se-2018/se-2018.github.io#21]
从网页上下载的资料包在路径
_MazeBug/mazeBug/info/gridworld/maze/MazeBug.java_ 以及 _MazeBug/mazeBug/info/gridworld/maze/MazeBugRunner.java_ 
已经存在源码了吧？

**Comment by LinJinghua** [comment]
改写其中方法完成任务

**Comment by Ernie1** [comment]
膜拜13大佬
