### ISSUE TITLE
关于N-puzzle的目标状态

### ISSUE THREAD

**Issue by lossatsea** [se-2018/se-2018.github.io#23]
N-puzzle的目标状态是不是都是从1到dimension * dimension - 1依次排列，空白格在最后。因为看到给的估价函数例子中是通过判断当前格子数是否等于下一个格子数-1来判断是否排列正确的。

**Comment by LinJinghua** [comment]
并没有做这个保证：目标状态必须是`{dimension * dimension, 1, 2, ... , dimension * dimension - 1,0}`。

那个例子就只是贪图方便写的。

但事实上这目标状态转换一下也就可以了，所以也不测试这个增加大家的代码量，所以最终测例中保证目标状态是`{dimension * dimension, 1, 2, ... , dimension * dimension - 1,0}`。
