### ISSUE TITLE
如何从Image中获取RGB值

### ISSUE THREAD

**Issue by CastleOnTheHill** [se-2018/se-2018.github.io#25]
使用BufferedImage 的getRGB方法，但发现是返回的值(temp)是负数（高8位全为0不可能是负数），检查了Read函数中pix数组都是正数。
如果是方法错了要使用什么方法来获取？
```
		BufferedImage bufferedImage = toBufferedImage(sourImage);
		int height = sourImage.getHeight(null);
		int width = sourImage.getWidth(null);
		int pix[] = new int[height * width];
		for(int h = 0; h < height; h++) {
			for(int w = 0; w < width; w++) {
				int temp = bufferedImage.getRGB(w, h);
				pix[h * width + w] = bufferedImage.getRGB(w, h) & 0x00FF0000 >> 16;
			}
		}
```

**Comment by vegchic** [comment]
[BufferedImage.getRGB](https://docs.oracle.com/javase/7/docs/api/java/awt/image/BufferedImage.html#getRGB(int,%20int))
> Returns an integer pixel in the default RGB color model (TYPE_INT_ARGB) and default sRGB colorspace. Color conversion takes place if this default model does not match the image ColorModel. There are only 8-bits of precision for each color component in the returned data when using this method.
返回的是ARGB？高8位为alpha

**Comment by dysuby** [comment]
[getRGB](https://docs.oracle.com/javase/7/docs/api/java/awt/image/BufferedImage.html#getRGB(int,%20int))
> Returns an integer pixel in the default RGB color model (TYPE_INT_ARGB) and default sRGB colorspace. 

附上<del>解决方案</del>才发现原来为1才正常，，
[stackoverflow](https://stackoverflow.com/a/25761567)
