### ISSUE TITLE
为什么修改MazeBug的代码不起作用？

### ISSUE THREAD

**Issue by chenf99** [se-2018/se-2018.github.io#26]
运行后的gridworld中的MazeBug依然是原始状态，添加的MazeBug也不行，LoadMap之后也不行，MazeBug都不能动

**Comment by LinJinghua** [comment]
jar包里的`MazeBug`覆盖了你写的`MazeBug`。删除jar包里的`MazeBug`或者确保你写的`MazeBug`类加载优先于jar包里的(一般是查找优先，即指定classpath)。

**Comment by chenf99** [comment]
删除jar包里的MazeBug就不能运行了，不知道为啥指定classpath也不行，也许我弄的不对吧，我只好重新生成jar包了

**Comment by LinJinghua** [comment]
@chenf99 如果还不行，建议了解`classpath`后再弄。

**Comment by CastleOnTheHill** [comment]
给出我的解决方案
1. 首先在命令行下编译 `MazeBug.java`  。`MazeBug.java`中需要有`package info.gridworld.maze`
2. 将生成的`MazeBug.class` 替换到`gridworld.jar` 中。

**Comment by Siriussee** [comment]
我的建议是，采用不需要jar的方法。
1. 首先在项目中`右键 - build path - configure build path - library`删除除了JRE之外的全部包
1. 然后删除src目录下的全部文件
1. 下载一份全新的GridWorldCode 和 MazeBug
1. 使用 MazeBug 中的 WorldFrame.java W......properties 代替 GridWorldCode/...../gui 中的对应文件
1. 将 MazeBug/..../gridworld 中的 maze 文件夹拖入  GridWorldCode/...../gridworld 文件夹
1. 回到 IDE，把 GridWorldCode 中的 info 文件夹拖入 IDE 的 src 即可

**Comment by zehaowang983** [comment]
生成新jar的方法：
1.用”WorldFrame.java”和”WorldFrameResources.properties”替换”GridWorldCode/GridWorldCode/framework/info/gridworld/gui”下面的对应的文件
2.将MazeBug/mazebug/info/gridworld中的maze文件夹放到GridWorldCode/framework/info/gridworld下
**当然你需要将更改完的MazeBug实现导入到maze目录里再进行下一步。**
**且要在前面加package info.gridworld.maze;**
3.切换到GridWorldCode/下（即有build.xml的目录）执行ant。
4.在GridWorldCode/dist/GridWorldCode/下即可发现新的gridworld.jar。
