### ISSUE TITLE
ImageIO里，Toolkit.getDefaultToolkit().createImage不能创建Image

### ISSUE THREAD

**Issue by cait7** [se-2018/se-2018.github.io#28]
在myRead里，我尝试调用Toolkit.getDefaultToolkit().createImage() 生成图像， 但不能有效读取， 然而经检验，RGB数组和其他参数都正确

**Comment by cait7** [comment]
不能有效读取是指在GUI界面，Open一个bmp图像，没有显示

**Comment by Gongzq5** [comment]
Console有报错信息吗？不如试一试同学的代码看看能否正常运行？

**Comment by cait7** [comment]
也不能正常运行，但是反复测试参数都是没问题的

**Comment by Alicizations** [comment]
拉大一下窗口?

**Comment by LinJinghua** [comment]
不能正常运行也不贴错误信息？

你不贴错误信息我可没办法。
