### ISSUE TITLE
Eclipse 包错误

### ISSUE THREAD

**Issue by Cai72** [se-2018/se-2018.github.io#29]
先提示 `Syntax error,parameterized types are only avaliable if source level is  1.5 or  greater`
把Compliance level改为1.5或更高后Library消失，自行导入jdk 1.8.0_91后
出现如下错误
```
The Type xx.xx.xx cannot be resolved.It is directly referenced from required .class files
1 quick fix available:
    Configure build path...
```
Windows环境下Eclipse正常，Linux下报错，[jdk 1.8.0_91] Compiler compliance level:1.7

**Comment by LinJinghua** [comment]
eclipse版本太低。

不用eclipse或者升级eclipse(云桌面l可换用/opt/resources目录下的eclipse)

**Comment by LinJinghua** [comment]
此外，课程要求是在linux平台开发。
