### ISSUE TITLE
云桌面junit命令行测试报错

### ISSUE THREAD

**Issue by hathcdy** [se-2018/se-2018.github.io#5]
提示包org.junit不存在；

**Comment by xwy27** [comment]
检查-cp 引用junit包路径是否正确

**Comment by xwy27** [comment]
vim ~/.bashrc
在文件末尾添加:
export JAVA_HOME=/usr/lib/jvm/jdk1.8.0_91
export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:/home/adminstrator/Downloads/junit-4.9.jar:$CLASSPATH
export PATH=$JAVA_HOME/bin:$JAVA_HOME/jre/bin:$PATH:$HOME/bin
保存后退出。其中，junit路径自己设置，按那个格式改好就行了。
source ~/.bashrc
路径生效，之后使用
javac MyTest.java
java org.junit.runner.JUnitCore  MyTest
即可成功运行

**Comment by huangjundashuaige** [comment]
java org.junit.runner.JUnitCore ./xx/test有同学知道吗

**Comment by hathcdy** [comment]
已解决 谢谢！

**Comment by Zophyr** [comment]
## 提供另一种思路

1. 将 `junit-4.9.jar` jar包放到`HelloWorld.java`和`HelloWorldTest.java`同一文件目录下
```shell
.
├── HelloWorld.java
├── HelloWorldTest.java
└── junit-4.9.jar

0 directories, 3 files
```
2. 命令行执行下述命令
```shell
$ javac -classpath .:junit-4.9.jar HelloWorldTest.java
$ java -classpath .:junit-4.9.jar -ea org.junit.runner.JUnitCore HelloWorldTest
```

~~如果云桌面每周还原，使用该方法可以避免每次都配置环境~~
